[workspace]
[package]
name = "powdr-openvm-matmul-test"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", branch = "support-sotfware-fallback" }

[profile.release-with-debug]
inherits = "release"
debug = true
