[package]
name = "powdr-number"
description = "powdr finite field definitions"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
ark-bn254 = { version = "0.4.0", default-features = false, features = [
    "scalar_field",
] }
ark-ff = "0.4.2"
ark-serialize = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
csv = "1.3"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive", "rc"] }
serde_with = "3.6.1"

[dev-dependencies]
test-log = "0.2.12"
env_logger = "0.10.0"
