[package]
name = "powdr-number"
description = "powdr finite field definitions"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
ark-bn254 = { version = "0.4.0", default-features = false, features = [
  "scalar_field",
] }
ark-ff = "0.4.2"
ark-serialize = "0.4.2"
p3-baby-bear = { git = "https://github.com/plonky3/Plonky3.git", rev = "2192432ddf28e7359dd2c577447886463e6124f0" }
p3-koala-bear = { git = "https://github.com/plonky3/Plonky3.git", rev = "2192432ddf28e7359dd2c577447886463e6124f0" }
p3-mersenne-31 = { git = "https://github.com/plonky3/Plonky3.git", rev = "2192432ddf28e7359dd2c577447886463e6124f0" }
p3-field = { git = "https://github.com/plonky3/Plonky3.git", rev = "2192432ddf28e7359dd2c577447886463e6124f0" }
num-bigint = { version = "0.4.3", features = ["serde"] }
num-traits.workspace = true
csv = "1.3"
serde = { version = "1.0", default-features = false, features = [
  "alloc",
  "derive",
  "rc",
] }
serde_with = "3.6.1"
schemars = { version = "0.8.16", features = ["preserve_order"] }
ibig = { version = "0.3.6", features = ["serde"] }
serde_cbor.workspace = true
derive_more.workspace = true

[dev-dependencies]
test-log.workspace = true
env_logger.workspace = true

[package.metadata.cargo-udeps.ignore]
development = ["env_logger"]

[lints]
workspace = true

[lib]
bench = false # See https://github.com/bheisler/criterion.rs/issues/458
