[workspace]
[package]
name = "powdr-openvm-guest-stdin-test"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "v1.4.1-powdr" }

[profile.release-with-debug]
inherits = "release"
debug = true
