[package]
name = "powdr-test"
description = "Tests and examples for the powdr crate"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
powdr.workspace = true

[dev-dependencies]
env_logger = "0.10.2"

[lints.clippy]
uninlined_format_args = "deny"
