[package]
name = "riscv_executor"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
itertools = "0.11"
ast = { path = "../ast" }
number = { path = "../number" }
parser = { path = "../parser" }
importer = { path = "../importer" }
analysis = { path = "../analysis" }
executor = { path = "../executor" }
