[package]
name = "powdr-openvm-hints-circuit"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []
aot = ["openvm-circuit/aot", "openvm-rv32im-circuit/aot"]
tco = ["openvm-circuit/tco", "openvm-rv32im-circuit/tco"]

[dependencies]
openvm-circuit = { workspace = true }
openvm-instructions = { workspace = true }
openvm-rv32im-circuit = { workspace = true }
openvm-stark-backend = { workspace = true }
openvm-stark-sdk = { workspace = true }
powdr-openvm-hints-transpiler = { workspace = true }
eyre.workspace = true
crypto-bigint = "0.6.1"
elliptic-curve = "0.13.8"
rand = { version = "0.8.5", default-features = false }
serde.workspace = true
