[workspace]
[package]
name = "openvm-ecc-test-programs"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", branch = "ovm-11-16", features = [
  "std",
] }
k256 = { version = "0.13", default-features = false, features = ["arithmetic"] }
hex-literal = "1.0.0"

