[package]
name = "sha256-example"
version = "0.0.0"
edition = "2021"

[workspace]
members = []

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", branch = "skip-dummy-wip" }
openvm-platform = { git = "https://github.com/powdr-labs/openvm.git", branch = "skip-dummy-wip" }
openvm-sha2 = { git = "https://github.com/powdr-labs/openvm.git", branch = "skip-dummy-wip" }
