[package]
name = "ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
num-bigint = "0.4.3"
number = { path = "../number" }
diff = "0.1"
log = "0.4.18"
derive_more = "0.99.17"

[dev-dependencies]
pretty_assertions = "1.3.0"


