[package]
name = "powdr-parser"
build = "build.rs"
description = "powdr parser"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
powdr-ast = { path = "../ast" }
powdr-number = { path = "../number" }
powdr-parser-util = { path = "../parser-util" }

lazy_static = "1.4.0"
lalrpop-util = {version = "^0.19", features = ["lexer"]}
num-bigint = "0.4.3"
num-traits = "0.2.15"
# This is only here to work around https://github.com/lalrpop/lalrpop/issues/750
# It should be removed once that workaround is no longer needed.
regex-syntax = { version = "0.6", default_features = false, features = ["unicode"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
test-log = "0.2.12"
env_logger = "0.10.0"

[build-dependencies]
lalrpop = "^0.19"
