[package]
name = "powdr-parser"
build = "build.rs"
description = "powdr parser"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
powdr-ast.workspace = true
powdr-number.workspace = true
powdr-parser-util.workspace = true

lazy_static = "1.4.0"
lalrpop-util = {version = "^0.19", features = ["lexer"]}
num-traits = "0.2.15"
derive_more = "0.99.17"

[dev-dependencies]
pretty_assertions = "1.4.0"
test-log = "0.2.12"
env_logger = "0.10.0"
walkdir = "2.4.0"
similar = "2.4"

[build-dependencies]
lalrpop = "^0.19"

[package.metadata.cargo-udeps.ignore]
development = ["env_logger"]

[lints]
workspace = true
