[package]
name = "keccak-example"
version = "0.0.0"
edition = "2021"

[workspace]
members = []

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", branch = "support-sotfware-fallback" }
openvm-platform = { git = "https://github.com/powdr-labs/openvm.git", branch = "support-sotfware-fallback" }
openvm-keccak256 = { git = "https://github.com/powdr-labs/openvm.git", branch = "support-sotfware-fallback" }
