[package]
name = "powdr_cli"
version = "0.1.0"
edition = "2021"

[features]
default = [] # halo2 is disabled by default

[dependencies]
clap = { version = "^4.3", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
compiler = { path = "../compiler" }
parser = { path = "../parser" }
riscv = { path = "../riscv" }
riscv_executor = { path = "../riscv_executor" }
number = { path = "../number" }
backend = { path = "../backend" }
pilopt = { path = "../pilopt" }
strum = { version = "0.24.1", features = ["derive"] }
clap-markdown = "0.1.3"

[dev-dependencies]
tempfile = "3.6"

[[bin]]
name = "powdr"
path = "src/main.rs"
