[package]
name = "powdr_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.1", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
compiler = { path = "../compiler" }
parser = { path = "../parser" }
riscv = { path = "../riscv" }
number = { path = "../number" }
halo2 = { path = "../halo2" }
strum = { version = "0.24.1", features = ["derive"] }

[[bin]]
name = "powdr"
path = "src/main.rs"
