[package]
name = "powdr_cli"
version = "0.1.0"
edition = "2021"

[features]
default = ["halo2"]
halo2 = ["dep:halo2", "backend/halo2", "compiler/halo2"]

[dependencies]
clap = { version = "^4.3", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
compiler = { path = "../compiler" }
parser = { path = "../parser" }
riscv = { path = "../riscv" }
number = { path = "../number" }
halo2 = { path = "../halo2", optional = true }
backend = { path = "../backend" }
pilopt = { path = "../pilopt" }
strum = { version = "0.24.1", features = ["derive"] }

[dev-dependencies]
tempfile = "3.6"

[[bin]]
name = "powdr"
path = "src/main.rs"
