[package]
name = "bberg"
version = "0.1.0"
authors = ["Maddiaa"]
edition = "2021"

[dependencies]
num-bigint = "0.4.3"

number = { path = "../number" }
num-traits = "0.2.15"
num-integer = "0.1.45"
itertools = "^0.10"
log = "0.4.17"
rand = "0.8.5"
ast = { version = "0.1.0", path = "../ast" }
