[package]
name = "powdr-pilopt"
description = "powdr-PIL optimizer"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
powdr-ast.workspace = true
powdr-number.workspace = true

log = "0.4.17"
pretty_assertions = "1.4.0"

[dev-dependencies]
powdr-pil-analyzer.workspace = true

[lints.clippy]
uninlined_format_args = "deny"
