[workspace]
[package]
name = "openvm-k256-ecrecover-programs"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", branch = "skip-dummy-wip", features = [
  "std",
] }
k256 = { git = "https://github.com/powdr-labs/elliptic-curves-k256", branch = "direct-to-apc", default-features = false, features = [
  "expose-field",
  "arithmetic",
  "ecdsa",
] }
hex-literal = { version = "0.4.1", default-features = false }
