
[workspace]
[package]
name = "openvm-ecc-test-programs"
version = "0.0.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/powdr-labs/openvm.git", rev = "v1.4.2-powdr-rc.1", features = [
  "std",
] }
openvm-ecc-guest = { git = "https://github.com/powdr-labs/openvm.git", rev = "v1.4.2-powdr-rc.1", subdirectory = "extensions/ecc/guest", default-features = false }
openvm-algebra-guest = { git = "https://github.com/powdr-labs/openvm.git", rev = "v1.4.2-powdr-rc.1", subdirectory = "extensions/algebra/guest", default-features = false }
openvm-k256 = { git = "https://github.com/powdr-labs/openvm.git", rev = "v1.4.2-powdr-rc.1", subdirectory = "guest-libs/k256", package = "k256", features = [
  "ecdsa",
] }

hex-literal = { version = "0.4.1", default-features = false }

